[package]
name = "opengl"
version = "0.1.0"
edition = "2024"

[dependencies]
glutin = "0.32.3"
glutin-winit = "0.5.0"
winit = "0.30.11"
gl = "0.14.0"
image = { version = "0.25.6", features = ["default"] }
nalgebra-glm = "0.19.0"
fastrand = "2.3.0"
log = "0.4.27"
thiserror = "1.0.69"
russimp = "3.2.1"
openxr = "0.19.0"
